events {
    worker_connections 1024;
}

http {
    # 1. إجبار Nginx على قراءة الـ IP الحقيقي من هيدر جوجل وتحديث الـ الـ Remote_Addr
    set_real_ip_from 0.0.0.0/0;
    real_ip_header X-Forwarded-For;

    server {
        listen 8080;

        location /@nkka404 {
            proxy_redirect off;
            proxy_pass http://35.171.3.190:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            
            # 2. تفعيل إرسال الـ IP الحقيقي (لي راه مخبأ ف الـ $remote_addr) للـ VPS
            proxy_protocol on;
        }
    }
}
